"""Add preprocess_applied to SonarImage

Revision ID: 205874d4afc2
Revises: 844a3dab0f59
Create Date: 2026-09-21 12:34:11.703381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205874d4afc2'
down_revision: Union[str, Sequence[str], None] = '844a3dab0f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sonar_images', sa.Column('preprocess_applied', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sonar_images', 'preprocess_applied')
    # ### end Alembic commands ###
