"""Initial migration

Revision ID: 844a3dab0f59
Revises: 
Create Date: 2026-09-21 12:31:22.763878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844a3dab0f59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=True),
    sa.Column('port_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('vessel_speed', sa.Float(), nullable=True),
    sa.Column('sonar_range', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_mission_id'), 'missions', ['mission_id'], unique=True)
    op.create_index(op.f('ix_missions_port_id'), 'missions', ['port_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Integer(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('image_processing_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('original_image_path', sa.String(), nullable=True),
    sa.Column('processed_image_path', sa.String(), nullable=True),
    sa.Column('quality_mask_path', sa.String(), nullable=True),
    sa.Column('inference_mask_path', sa.String(), nullable=True),
    sa.Column('shadow_overlay_path', sa.String(), nullable=True),
    sa.Column('quality_assessment', sa.String(), nullable=True),
    sa.Column('mask_statistics', sa.String(), nullable=True),
    sa.Column('region_analysis', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('warnings', sa.String(), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sonar_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('original_path', sa.String(), nullable=True),
    sa.Column('processed_path', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=True),
    sa.Column('sonar_image_id', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('bbox_x2', sa.Float(), nullable=True),
    sa.Column('bbox_y2', sa.Float(), nullable=True),
    sa.Column('mask', sa.String(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('seabed_nature', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('dataset_version', sa.String(), nullable=True),
    sa.Column('location_source', sa.String(), nullable=True),
    sa.Column('coordinate_uncertainty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['sonar_image_id'], ['sonar_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=True),
    sa.Column('detection_id', sa.String(), nullable=True),
    sa.Column('port_id', sa.String(), nullable=True),
    sa.Column('anomaly_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('seabed_nature', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('coordinate_status', sa.String(), nullable=True),
    sa.Column('coordinate_validation_reason', sa.Text(), nullable=True),
    sa.Column('original_latitude', sa.Float(), nullable=True),
    sa.Column('original_longitude', sa.Float(), nullable=True),
    sa.Column('is_water_validated', sa.Boolean(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('dataset_version', sa.String(), nullable=True),
    sa.Column('location_source', sa.String(), nullable=True),
    sa.Column('coordinate_uncertainty', sa.Float(), nullable=True),
    sa.Column('optical_image_path', sa.String(), nullable=True),
    sa.Column('optical_classification', sa.String(), nullable=True),
    sa.Column('optical_confidence', sa.Float(), nullable=True),
    sa.Column('final_classification', sa.String(), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_anomaly_id'), 'anomalies', ['anomaly_id'], unique=True)
    op.create_index(op.f('ix_anomalies_coordinate_status'), 'anomalies', ['coordinate_status'], unique=False)
    op.create_index(op.f('ix_anomalies_is_water_validated'), 'anomalies', ['is_water_validated'], unique=False)
    op.create_index(op.f('ix_anomalies_port_id'), 'anomalies', ['port_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomalies_port_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_is_water_validated'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_coordinate_status'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_table('detections')
    op.drop_table('sonar_images')
    op.drop_table('reports')
    op.drop_table('image_processing_jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_missions_port_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_mission_id'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
